"""updated bird to eliminate userid requirement and comment out code

Revision ID: 205b4840b9bf
Revises: 66d99c1feb25
Create Date: 2021-10-15 09:53:03.380711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b4840b9bf'
down_revision = '66d99c1feb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('birds_user_id_fkey', 'birds', type_='foreignkey')
    op.drop_column('birds', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('birds_user_id_fkey', 'birds', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
