"""empty message

Revision ID: 4b41844a463f
Revises: a21380974051
Create Date: 2021-10-12 11:24:21.286947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b41844a463f'
down_revision = 'a21380974051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('bird_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bird_id'], ['birds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment')
    )
    op.add_column('birds', sa.Column('bird_type', sa.String(length=255), nullable=False))
    op.add_column('birds', sa.Column('color', sa.String(length=255), nullable=False))
    op.add_column('birds', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('birds_comment_key', 'birds', type_='unique')
    op.create_unique_constraint(None, 'birds', ['bird_type'])
    op.create_unique_constraint(None, 'birds', ['color'])
    op.drop_constraint('birds_bird_id_fkey', 'birds', type_='foreignkey')
    op.create_foreign_key(None, 'birds', 'users', ['user_id'], ['id'])
    op.drop_column('birds', 'comment')
    op.drop_column('birds', 'bird_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('bird_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('birds', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'birds', type_='foreignkey')
    op.create_foreign_key('birds_bird_id_fkey', 'birds', 'birds', ['bird_id'], ['id'])
    op.drop_constraint(None, 'birds', type_='unique')
    op.drop_constraint(None, 'birds', type_='unique')
    op.create_unique_constraint('birds_comment_key', 'birds', ['comment'])
    op.drop_column('birds', 'user_id')
    op.drop_column('birds', 'color')
    op.drop_column('birds', 'bird_type')
    op.drop_table('comments')
    # ### end Alembic commands ###
