"""removed primary joined from comment reaource as there is no relationships

Revision ID: fe024f88861f
Revises: 90b361d75d24
Create Date: 2021-10-16 16:36:15.770292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe024f88861f'
down_revision = '90b361d75d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('bird_type', sa.String(length=255), nullable=False))
    op.drop_constraint('comments_bird_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'bird_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('bird_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_bird_id_fkey', 'comments', 'birds', ['bird_id'], ['id'])
    op.drop_column('comments', 'bird_type')
    # ### end Alembic commands ###
